services:
  mongo:
    image: mongo:latest
    container_name: sample-db
    ports:
      - 27017:27017
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data: